const MODULE_ACCESS_POLICY = {
  super_admin: {
    audit: ['read'],
    projects: ['read', 'create', 'update', 'delete'],
    attendance: ['read', 'create', 'update'],
    labor_permissions: ['read', 'create', 'update', 'delete'],
    activities: ['read', 'create', 'update', 'delete'],
    users: ['read', 'create', 'update', 'delete'],
    employees: ['read', 'create', 'update', 'delete'],
    allowances: ['read', 'create', 'update', 'delete'],
    materials: ['read', 'create', 'update', 'delete'],
    warehouse: ['read', 'create', 'update', 'delete'],
    commercial: ['read', 'create', 'update', 'delete'],
    operational_scopes: ['read', 'create', 'update', 'delete'],
    hse: ['read', 'create', 'update', 'delete'],
    tasks: ['read', 'create', 'update', 'delete'],
    performance: ['read', 'create', 'update', 'delete'],
    dashboard: ['read'],
  },
  administrative: {
    audit: ['read'],
    projects: ['read', 'create', 'update', 'delete'],
    attendance: ['read', 'create', 'update'],
    labor_permissions: ['read', 'create', 'update', 'delete'],
    activities: ['read', 'create', 'update', 'delete'],
    users: ['read', 'create', 'update', 'delete'],
    employees: ['read', 'create', 'update', 'delete'],
    allowances: ['read', 'create', 'update', 'delete'],
    materials: ['read', 'create', 'update', 'delete'],
    warehouse: ['read', 'create', 'update', 'delete'],
    commercial: ['read', 'create', 'update', 'delete'],
    operational_scopes: ['read', 'create', 'update', 'delete'],
    hse: ['read', 'create', 'update', 'delete'],
    tasks: ['read', 'create', 'update', 'delete'],
    performance: ['read', 'create', 'update', 'delete'],
    dashboard: ['read'],
  },
  coordinator_operations: {
    audit: ['read'],
    projects: ['read', 'create', 'update'],
    attendance: ['read', 'create', 'update'],
    employees: ['read'],
    labor_permissions: ['read', 'create', 'update'],
    activities: ['read', 'create', 'update', 'delete'],
    allowances: ['read'],
    warehouse: ['read', 'create', 'update'],
    commercial: ['read', 'create', 'update'],
    hse: ['read', 'create', 'update'],
    tasks: ['read', 'create', 'update', 'delete'],
    performance: ['read', 'create', 'update'],
  },
  supervisor: {
    projects: ['read'],
    attendance: ['read', 'create', 'update'],
    activities: ['read', 'update'],
    allowances: ['read', 'update'],
    materials: ['read', 'create', 'update'],
    warehouse: ['read', 'create', 'update'],
    commercial: ['read', 'create', 'update'],
    hse: ['read', 'create', 'update'],
    tasks: ['read', 'create', 'update'],
    performance: ['read', 'create', 'update'],
  },
  leader: {
    projects: ['read'],
    attendance: ['read', 'create', 'update'],
    activities: ['read', 'update'],
    allowances: ['read', 'update'],
    materials: ['read', 'create', 'update'],
    warehouse: ['read', 'create', 'update'],
    commercial: ['read', 'create', 'update'],
    hse: ['read', 'create', 'update'],
    tasks: ['read', 'create', 'update'],
    performance: ['read', 'create', 'update'],
  },
  employee: {
    attendance: ['read', 'create', 'update'],
    activities: ['read'],
    hse: ['read', 'create'],
    tasks: ['read', 'update'],
  },
  warehouse_logistics: {
    attendance: ['read', 'create', 'update'],
    projects: ['read'],
    warehouse: ['read', 'create', 'update'],
  },
  commercial: {
    attendance: ['read', 'create', 'update'],
    projects: ['read'],
    allowances: ['read', 'create', 'update'],
    commercial: ['read', 'create', 'update'],
  },
  gerencial: {
    dashboard: ['read'],
    projects: ['read'],
    attendance: ['read', 'create', 'update'],
    employees: ['read'],
    activities: ['read'],
    allowances: ['read'],
    warehouse: ['read'],
    commercial: ['read', 'update'],
    hse: ['read'],
    tasks: ['read'],
    performance: ['read'],
  },
  hse: {
    attendance: ['read', 'create', 'update'],
    hse: ['read', 'create', 'update', 'delete'],
    projects: ['read'],
    employees: ['read'],
  },
};

module.exports = {
  MODULE_ACCESS_POLICY,
};
